### ISSUE TITLE
Latest update doesn't work with club Nintendo snes controller for Wii

### ISSUE THREAD

**Issue by baco81** [SuperrSonic/RA-SS#12]
Hello Superrsonic!
Very welcome update. Thanks!
Unfortunately, this last release doesn't work with the club Nintendo Snes controller for Wii. When I attach this controller to the wiimote, It's like I had the down direction pressed all the time.

Something similar happened recently to the Snes9xgx emulator and was solved in this commit:
https://github.com/dborth/snes9xgx/commit/dc4d93d00653e7d129cf642e5277e05900192158
Please help!
Thank you.

**Comment by SuperrSonic** [comment]
Since this has to do with the control stick try increasing _Axis Threshold_, RA officially uses 0.5, I lowered it because my GameCube controllers felt too unresponsive.

![00000000-45](https://user-images.githubusercontent.com/6880539/55917417-3fde7180-5bbd-11e9-938a-45fb58ee1f40.png)

**Comment by baco81** [comment]
Hi Superrsonic
I followed your recommendation but it didn't work.
Besides, if I set an axis threshold or modify any other config setting through the menu, it won't stick. Do I need to set it manually in the config file?

**Comment by SuperrSonic** [comment]
Every setting should save. If you go to sd:/private/other/ do you see a main.cfg file? I'd like to know if it's related to writing. If you're missing this file then I'll post a build for you to try and see if that's the problem.

For the controller issue, you're saying this doesn't happen on other versions of RA, right? You could try disabling the control stick mappings (you clear them by pressing plus on the wiimote).

**Comment by baco81** [comment]
I didn't know that I was supposed to create those folders myself. I just thought that I could set a path in the settings menu and be done with it. It'll create those folders and see what happens.

I haven't tried the last few versions of RA, but I can tell that 1.0.0.2 and a few others worked well (1.22, 1.36...). Even the older RA-SS worked well with the controller. Anyway, I tried disabling the analog sticks mappings and it didn't help. Maybe is it related to the compilation toolchain? It's strange that the last versions of snes9xgx suffered from the same issue not long ago...

**Comment by SuperrSonic** [comment]
It should create the folders and files just like it did in previous versions. I don't have those issues, but they might be caused by a small change that evidently only affects some devices. It was removed because in theory it was causing a rare crash when loading big roms from zip/7z files and it would crash cleaning up on exit.

The new update should fix this, please let me know.  For the SNES pad issue please test the build attached.
[gambatte_cc.zip](https://github.com/SuperrSonic/RA-SS/files/3100103/gambatte_cc.zip)

**Comment by SuperrSonic** [comment]
New update is out, it essentially copy pastes the snes9xgx fix so hoping it fixed your issue.

RA folder checking was out of order, it should now always start with the base directory, this should fix the settings not being saved.

WonderSwan, Pokemini, and Handy are now using tweaked video code to prevent screen tearing, but causes flickering to the fps counter.

Exposed two hidden settings to the interface; hide cursor "> " and change the horizontal position of the clock.

**Comment by baco81** [comment]
Thank you very much for the info. I have limited time during weekdays but it'll try as soon as possible the new version.

**Comment by baco81** [comment]
Ok, I couldn't resist and tried the new version. I am glad to say that the issue with the club nintendo snes controller is solved. Thank you very much!
Regarding saving the config, I am afraid to inform you that the issue still persists, but I think that should go in a new issue thread. You can close this one. Thank you again!

**Comment by SuperrSonic** [comment]
I was able to reproduce it, should be working now.

**Comment by baco81** [comment]
I have found that the controller doesn't work at all with the fceumm core. Could you check it, please?

Regarding the settings saving issue, now it saves as it is supposed to. Thanks!!

**Comment by SuperrSonic** [comment]
For the fceumm core, when a game is loaded if you go to input and select Gamepad under "Device Type" it should work.

It defaults to Auto but for some reason fails, I could just change it to always default to Gamepad but I want to avoid as many core specific changes as possible and this gets saved anyway so I figured it would be OK.

**Comment by baco81** [comment]
Oh, I see, I didn't know about that.

Maybe a known issues list in the readme file would be a good thing to have in order to avoid opening unnecessary issue threads.

Thank you for clarifying this. Have a good weekend.

**Comment by SuperrSonic** [comment]
Went ahead and fixed it, also added a core setting to change sample rate as it was hardcoded to 32000 now it will start in 48000 and can be lowered to 8000 which seems to increase speed, useful when using CPU filters.

**Comment by baco81** [comment]
Thank you Superrsonic. It'll give it a try.
